#define MENU_X_JUMP 5
#define MENU_Y_JUMP 5
#define TEXT_BOX_Y_POSITION 5
#define CHECK_BOX_Y_POSITION 10
#define OFFEST_LABLES_INPUT 20
#define FORGROUND_SELECTED 
#define WHITE_FOREGROUND_COLOR FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_INTENSITY
#define WHITE_BACKGROUND_COLOR BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_RED | BACKGROUND_INTENSITY 
#define SELECTED_BACKGROUND BACKGROUND_INTENSITY